FROM node:slim

WORKDIR /usr/src/app

ARG NODE_ENV=hom

ENV NODE_ENV=${NODE_ENV}

COPY . .

RUN npm install sequelize -D sequelize-cli
RUN npx sequelize db:migrate --env "homologation"

RUN npm install --loglevel verbose
RUN npm run build

EXPOSE 2000
CMD DOTENV_CONFIG_PATH=.env.${NODE_ENV} node -r dotenv/config dist/main.js